export const ENTRY_EMAIL_MAX_LENGTH = 50;

export const ENTRY_COMMENT_MAX_LENGTH = 200;

export const ENTRY_GAME_TITLE_MAX_LENGTH = 100;

export const ENTRY_GAME_GENRE_MAX_LENGTH = 50;

export const ENTRY_GAME_DESCRIPTION_MAX_LENGTH = 200;

export const ENTRY_GAME_TOOLS_MAX_LENGTH = 100;

export const ENTRY_GAME_ARCHIVE_LINK_MAX_LENGTH = 100;

export const ENTRY_GAME_SCREENSHOT_LINK_MAX_LENGTH = 100;
